### ISSUE TITLE
Update for GitBucket 4.35.1

### ISSUE THREAD

**Issue by GabrieleFrau** [gitbucket/gitbucket-notifications-plugin#21]
java.lang.NoSuchMethodError: `gitbucket.core.html.main$.apply(Ljava/lang/String;Lscala/Option;Lplay/twirl/api/Html;Lgitbucket/core/controller/Context;)Lplay/twirl/api/Html;`

**Comment by SIkebe** [comment]
@takezoe The new version of gitbucket-notifications-plugin (v1.10.0) should be bundled with GitBucket 4.35.X?
https://github.com/gitbucket/gitbucket/blob/d4a892bf7fd9ffa068cdbb8c989dfd56aecd7c36/src/main/resources/bundle-plugins.txt#L1

**Comment by takezoe** [comment]
Right. I will release 4.35.2. https://github.com/gitbucket/gitbucket/pull/2616

**Comment by SIkebe** [comment]
@takezoe Thanks!
