### ISSUE TITLE
Make Mail FROM name customizable

### ISSUE THREAD

**Issue by bituze** [gitbucket/gitbucket-notifications-plugin#24]
Is there a way to make the email **FROM name** variable depending on the user doing the action ? 
For example instead of being a static text it could be the user fullname.

**Comment by takezoe** [comment]
Unfortunately, FROM name is a global setting in GitBucket core. Currently, there is not way to customize it from plugins.

**Comment by bituze** [comment]
> Unfortunately, FROM name is a global setting in GitBucket core. Currently, there is no way to customize it from plugins.

Thank you for your reply @takezoe .
