### ISSUE TITLE
Always error in notification plugin, configuring SMTP

### ISSUE THREAD

**Issue by jmym** [gitbucket/gitbucket-notifications-plugin#8]
Hi, I use the version war file runing in windows 10, I use the plugin notification 1.4.0, and in the System Setings i configure the smtp and always give me the same error:
[Error] org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587

I use telnet smpt.gmail.com and is working.
![captura notification](https://user-images.githubusercontent.com/32701195/35731939-dd9674f4-0817-11e8-90d8-ea61f0651d34.JPG)

**Comment by shimamoto** [comment]
If STARTTLS flag is enabled, being disabled SSL one would likely work.

**Comment by jmym** [comment]
I test it, but the same result.

**Comment by shimamoto** [comment]
Didn't you receive a "Review blocked sign-in attempt" email?

**Comment by jmym** [comment]
I dont received nothing, my maillist it's empty. Only show me this: [Error] org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587

**Comment by shimamoto** [comment]
I have confirmed that it works with the latest versions (gitbucket 4.21.2 and gitbucket-notifications-plugin 1.4.0). Please check whether you can receive the test mail.
<img width="1280" alt="smtp-setting" src="https://user-images.githubusercontent.com/1875052/36536854-c626102c-1811-11e8-9e98-7f3a7f859a6c.png">

**Comment by jmym** [comment]
Ok the problem was fixed.

I disable the firewall - antivirus, and work correctly.

Best Regards,
JM

2018-02-22 12:49 GMT+01:00 takako shimamoto <notifications@github.com>:
